Update autotag.yml

diff --git a/.github/workflows/autotag.yml b/.github/workflows/autotag.yml
--- a/.github/workflows/autotag.yml
+++ b/.github/workflows/autotag.yml
@@ -41,26 +41,27 @@ jobs:
       - name: Tag patch release
         run: |
           # Tag patch release
+          
           MINOR_BRANCH=$(php -r 'echo substr("${{ github.ref }}", 11);')
+          if ! [[ "$MINOR_BRANCH" =~ ^[0-9]+\.[0-9]+$ ]]; then echo "Invalid minor branch $MINOR_BRANCH, existing" && exit 1; fi
                               
           # Get the current patch number
-          /usr/bin/git tag >> tags.txt
+          git tag > __tags.txt
           cat << EOF > __run.php
           <?php
           \$arr = [];
-          foreach (explode("\n", file_get_contents('tags.txt')) as \$tag) {
+          foreach (explode("\n", file_get_contents('__tags.txt')) as \$tag) {
             if (!preg_match('#^([0-9]+)\.([0-9]+)\.([0-9]+)\$#', \$tag, \$m)) continue;
             list(\$z, \$a, \$b, \$c) = \$m;
             if ("\$a.\$b" != '$MINOR_BRANCH') continue;
             \$arr[] = (int) "\$c";
           }
-          if (count(\$arr) == 0) exit(0);
           sort(\$arr);
-          echo \$arr[count(\$arr) - 1];
+          if (count(\$arr) > 0) echo \$arr[count(\$arr) - 1];
           EOF
-          CURR_PATCH_N=$(php __run.php)
           
-          if [ "$CURR_PATCH_N" == "" ]; then echo "No existing semver tag found for minor branch $MINOR_BRANCH, exiting" && exit 0; fi
+          CURR_PATCH_N=$(php __run.php)
+          if [ "$CURR_PATCH_N" == "" ]; then CURR_PATCH_N="$MINOR_BRANCH.0"; fi
           NEXT_PATCH_N=$((CURR_PATCH_N+1))
           TAG="$MINOR_BRANCH.$NEXT_PATCH_N"
           
